project:
  type: website

website:
  description: "Babbling about Bioinformatics"
  site-url: https://your-website-url.example.com # you must change this appropriately for RSS feeds to work properly
  title: "Sadie Wisotsky: Bioinfomatician"
  navbar:
    right:
      - about.qmd
      - icon: linkedin
        text: LinkedIn
        href: https://www.linkedin.com/in/sadie-wisotsky/
      - icon: github
        text: Github
        href: https://github.com/srwis
format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css



